# GitHub Actions 工作流程：部署静态网站到七牛云对象存储 Kodo
# 最终简化版 - 直接在脚本中修改 Bucket 名称

name: Deploy Website to Qiniu Cloud (qshell)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 第 1 步：拉取你的 GitHub 仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第 2 步：构建你的网站
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies and Build Project
        run: |
          npm install
          npm run build 

      # 第 3 步：使用 qshell 上传文件并设置缓存策略
      - name: Upload to Kodo and Set Cache with qshell
        run: |
          # --- 准备工作 ---
          echo "Downloading and setting up qshell..."
          wget https://github.com/qiniu/qshell/releases/download/v2.10.0/qshell-v2.10.0-linux-amd64.tar.gz -O qshell.tar.gz
          tar -xvf qshell.tar.gz
          mv qshell-v2.10.0-linux-amd64 qshell
          chmod +x qshell
          
          echo "Configuring qshell account..."
          ./qshell account ${{ secrets.QINIU_ACCESS_KEY }} ${{ secrets.QINIU_SECRET_KEY }} deploy_user
          
          # --- 上传文件 ---
          echo "Uploading files from 'docs' directory..."
          # 创建 qshell 上传配置文件
          cat > qupload.json << EOF
          {
              "src_dir": "docs",
              "bucket": "your-real-bucket-name",
              "overwrite": true,
              "rescan_local": true
          }
          EOF
          
          # TODO: 把上一行的 "your-real-bucket-name" 替换成你真实的 Bucket 名称

          # 执行上传，10是并发线程数
          ./qshell qupload 10 qupload.json

          # --- 设置缓存 ---
          echo "Setting 'no-cache' for all HTML files..."
          # TODO: 把下一行的 "your-real-bucket-name" 替换成你真实的 Bucket 名称
          BUCKET_NAME="emc-website-dev-zh-cn"
          
          ./qshell listbucket $BUCKET_NAME | grep '\.html$' | awk '{print $1}' | while read key; do
            echo "Setting 'Cache-Control: no-cache' for file: $key"
            ./qshell chgm $BUCKET_NAME "$key" 'Cache-Control: no-cache'
          done

          echo "Deployment process completed successfully."
