# GitHub Actions 工作流程：部署静态网站到七牛云对象存储 Kodo
# 调试版本 - 隔离 Secrets 问题

name: DEBUG - Deploy Website to Qiniu Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 第 1 步：拉取你的 GitHub 仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第 2 步：构建你的网站
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies and Build Project
        run: |
          npm install
          npm run build 

      # 第 3 步：调试 qshell 脚本
      - name: DEBUG - qshell execution step
        run: |
          echo "--- DEBUG: Step 3 has started. If you see this, the script block is valid. ---"

          # --- 准备工作 ---
          echo "DEBUG: Downloading and setting up qshell..."
          wget https://github.com/qiniu/qshell/releases/download/v2.10.0/qshell-v2.10.0-linux-amd64.tar.gz -O qshell.tar.gz
          tar -xvf qshell.tar.gz
          mv qshell-v2.10.0-linux-amd64 qshell
          chmod +x qshell
          echo "DEBUG: qshell setup is complete."
          
          echo "DEBUG: SKIPPING qshell account command to isolate secret injection issue."
          # 下面这行被注释掉了，因为它使用了 secrets
          # ./qshell account ${{ secrets.QINIU_ACCESS_KEY }} ${{ secrets.QINIU_SECRET_KEY }} deploy_user
          
          echo "DEBUG: Preparing to run a qshell command that will fail."
          echo "DEBUG: We EXPECT to see an error message from qshell itself, not a silent exit 254."

          # 我们尝试执行一个需要账户的命令。它应该会失败，但会打印出 "no account configured" 之类的错误。
          ./qshell user ls

          echo "DEBUG: If you see this message, it means the script ran to completion."
