# 最终方案 v12：修正 CDN 刷新 URL，确保包含域名
name: Deploy ONLY HTML to Qiniu

on:
  push:
    branches:
      - main

jobs:
  deploy-html-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload ONLY HTML files to Qiniu
        env:
          QINIU_BUCKET_NAME: ${{ secrets.QINIU_BUCKET_NAME }}
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_DOMAIN: ${{ secrets.QINIU_DOMAIN }}
        run: |
          # --- 步骤 1, 2, 3 保持不变 ---
          echo "Downloading and setting up qshell..."
          wget https://github.com/qiniu/qshell/releases/download/v2.16.0/qshell-v2.16.0-linux-amd64.tar.gz -O qshell.tar.gz
          tar -xvf qshell.tar.gz
          chmod +x qshell
          ./qshell account $QINIU_ACCESS_KEY $QINIU_SECRET_KEY deploy_user

          echo "Creating a temporary directory with only HTML files..."
          TARGET_DIR="html_only"
          mkdir -p $TARGET_DIR
          find docs -type f -name "*.html" | while read -r filepath; do
            mkdir -p "$TARGET_DIR/$(dirname "$filepath")"
            cp "$filepath" "$TARGET_DIR/$filepath"
          done
          
          echo "Uploading the temporary directory..."
          cat > qupload-html.json << EOF
          {
              "src_dir": "$TARGET_DIR/docs",
              "bucket": "$QINIU_BUCKET_NAME",
              "overwrite": true,
              "rescan_local": true,
              "log_level": "info"
          }
          EOF
          ./qshell qupload -c 10 qupload-html.json

          # --- 4. 核心修正：在生成刷新列表时，重新加入域名 ---
          echo "Refreshing CDN cache for HTML files..."
          find docs -type f -name "*.html" | sed 's/docs\///' > html-files.txt
          
          # 创建一个空的刷新列表文件
          > urls_to_refresh.txt

          # 循环处理每个html文件
          cat html-files.txt | while read -r filepath; do
            path_no_index=$(echo "$filepath" | sed 's/index\.html$//')
            path_no_ext=$(echo "$path_no_index" | sed 's/\.html$//')
            
            # 生成带斜杠的 URL (目录)
            if [ "${path_no_index: -1}" == "/" ]; then
              echo "${QINIU_DOMAIN}${path_no_index}" >> urls_to_refresh.txt
            fi
            
            # 生成不带斜杠的 URL (文件或目录的别名)
            # 确保不重复添加
            if [ "$path_no_ext" != "$path_no_index" ]; then
               echo "${QINIU_DOMAIN}${path_no_ext}" >> urls_to_refresh.txt
            fi
          done
          
          # 单独处理根目录的 index.html
          if grep -q "^index.html$" html-files.txt; then
            echo "$QINIU_DOMAIN" >> urls_to_refresh.txt
          fi

          # 去重
          sort -u urls_to_refresh.txt -o urls_to_refresh.txt

          echo "--- URLs to be refreshed ---"
          cat urls_to_refresh.txt
          
          # 启用刷新!
          echo "Executing CDN refresh..."
          ./qshell cdnrefresh -i urls_to_refresh.txt

          echo "HTML-only deployment completed successfully."
