name: Deploy Static Website to Qiniu Cloud (qshell)

on:
  push:
    branches:
      - main   # ⚠️ 根据实际修改：比如你用 pages 分支，就写 pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # TODO: 修改成你的七牛 bucket 名
      QINIU_BUCKET_NAME: emc-website-dev-zh-cn

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and configure qshell
        run: |
          echo "Downloading qshell..."
          wget -O qshell.tar.gz https://github.com/qiniu/qshell/releases/download/v2.10.0/qshell-v2.10.0-linux-amd64.tar.gz
          
          echo "Unpacking..."
          tar -zxvf qshell.tar.gz
          
          echo "Check unpacked files:"
          ls -l qshell-v2.10.0-linux-amd64
          
          echo "Add execute permission..."
          chmod +x qshell-v2.10.0-linux-amd64/qshell
          
          echo "Configure qshell account..."
          ./qshell-v2.10.0-linux-amd64/qshell account "${{ secrets.QINIU_ACCESS_KEY }}" "${{ secrets.QINIU_SECRET_KEY }}" deploy_user

      - name: Upload static files to Qiniu
        run: |
          echo "Start uploading..."
          ./qshell-v2.10.0-linux-amd64/qshell qupload2 \
            --src-dir=docs \                  # ⚠️ 如果静态文件在根目录就写 .
            --bucket=${QINIU_BUCKET_NAME} \
            --overwrite

      - name: Set Cache-Control no-cache for all HTML files
        run: |
          echo "Set no-cache for HTML files..."
          ./qshell-v2.10.0-linux-amd64/qshell listbucket ${QINIU_BUCKET_NAME} --limit 10000 | grep '\.html$' | \
          xargs -I {} ./qshell-v2.10.0-linux-amd64/qshell chgm ${QINIU_BUCKET_NAME} {} 'Cache-Control: no-cache'

      - name: Done
        run: echo "✅ Deployment to Qiniu finished successfully!"
