# 混合方案 v3：使用双重保险模式精确上传 HTML
name: Deploy HTML to Qiniu (Assets via GitHub Pages)

on:
  push:
    branches:
      - main

jobs:
  deploy-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload HTML files to Qiniu
        env:
          QINIU_BUCKET_NAME: ${{ secrets.QINIU_BUCKET_NAME }}
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
        run: |
          # --- 准备工作 (下载并配置 qshell) ---
          echo "Downloading and setting up qshell v2.16.0..."
          wget https://github.com/qiniu/qshell/releases/download/v2.16.0/qshell-v2.16.0-linux-amd64.tar.gz -O qshell.tar.gz
          tar -xvf qshell.tar.gz
          chmod +x qshell
          
          echo "Configuring qshell account..."
          ./qshell account $QINIU_ACCESS_KEY $QINIU_SECRET_KEY deploy_user

          # --- 上传 HTML 文件 (使用双重保险) ---
          echo "Uploading only HTML files to Qiniu using double insurance..."
          cat > qupload-html.json << EOF
          {
              "src_dir": "docs",
              "bucket": "$QINIU_BUCKET_NAME",
              "overwrite": true,
              "rescan_local": true,
              "log_level": "info",
              "ignore_patterns": [
                  "*.js",
                  "*.css",
                  "*.png",
                  "*.jpg",
                  "*.jpeg",
                  "*.gif",
                  "*.svg",
                  "*.webp",
                  "*.ico",
                  "*.json",
                  "*.txt",
                  "*.md"
              ],
              "include_patterns": [
                  "*.html"
              ]
          }
          EOF
          
          ./qshell qupload -c 10 qupload-html.json

          # --- 刷新 CDN 缓存 ---
          echo "Refreshing CDN cache for HTML files..."
          find docs -type f -name "*.html" | sed 's/docs\///' > html-files.txt
          sed -e 's/index\.html$//' -e 's/\.html$//' html-files.txt | awk -v domain="https://your-domain.com/" '{print domain$0}' > urls_to_refresh.txt
          
          echo "--- URLs to be refreshed ---"
          cat urls_to_refresh.txt
          
          # 执行刷新, 请在确认无误后取消注释
          # ./qshell cdnrefresh -i urls_to_refresh.txt

          echo "HTML deployment and CDN refresh completed."
