name: Ultimate Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - A simple echo command
        run: |
          echo "Hello from the debug workflow!"
          echo "If you can see this message, the basic runner is working."

      - name: Step 2 - Checkout code and list files
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          echo "Listing files and directories:"
          ls -laR
